name: dewbiapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.0
  firebase_database: ^10.2.6
  cloud_firestore: ^4.9.2
  shared_preferences: ^2.2.1
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  permission_handler: ^11.0.0
  location_geocoder: ^1.0.5
  url_launcher: ^6.1.14
  google_sign_in: ^6.1.5
  flutter_linkify: ^6.0.0
  carousel_slider: ^4.2.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.8
  provider: ^6.0.5
  kpostal: ^0.5.1
  remedi_kopo: ^0.0.2
  flutter_naver_map: ^1.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700